version: '3'

services:
  api:
    container_name: shopping-list-api
    build:
      context: .
    volumes:
      - .:/srv/app:rw
    ports:
      - "3000:3000"
    entrypoint: "./docker-entrypoint.sh"

  db:
    container_name: shopping-list-db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=shopping-list
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - shopping-list-db:/var/lib/mysql

  adminer:
    container_name: shopping-list-adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  shopping-list-db: {}